name: Codacy Coverage Reporter

on:
  workflow_run:
    workflows:
      - Build and Test
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  report-coverage:
    if: github.repository == 'btcpay-monero/btcpayserver-monero-plugin'
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          github-token: ${{ secrets.API_GITHUB }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: dotcover.xml